### ISSUE TITLE
[Bug] User can logout of Aonsoku even after Autologin is set

### ISSUE THREAD

**Issue by kobayashi90** [victoralvesf/aonsoku#102]
Like ive previously described in #101 certain conditions allow the User to access Aonsoku on Mobile if people enable the Desktop Mode on Android or iPhone Devices (not sure about iOS tho). Here is proof of said Bug below.

![](https://i.imgur.com/juqacNO.png)

**Comment by victoralvesf** [comment]
I'm testing with an Android device running Chrome and this doesn't happen. Even accessing your instance (`squidify.org`).

**Steps:**
1. Access the app, saw the unsupported message
2. Requested Desktop Site
3. Opened user dropdown

**Result:** Logout option is not presented.

Even when navigating to other pages this doesn't change, the logout option remains hidden (theoretically not even listed in the DOM).

Did you do anything different?

Later today I'll be able to test with a different device.

**Comment by kobayashi90** [comment]
> **PS.** If this is indeed happening with certain devices, I don't think it's related to #101.

I would think its old cache, that thats horrible to resolve on mobile devices because they seem to not get fixed even after deleting the cache on the device itself..

**Comment by kobayashi90** [comment]
Update #1: give me some time to look into this more..

**Comment by victoralvesf** [comment]
I just tested with another device today and still can't find this bug. I'll be closing this issue for now, If you find something new, please reopen with more details.
