### ISSUE TITLE
[Bug] Autologin User can delete User Playlists from Other Users

### ISSUE THREAD

**Issue by kobayashi90** [victoralvesf/aonsoku#103]
How the Title already hint at, an Autologged in User with no Admin Priviliges can delete Admin generated Playlists.
How to replicate:

- Create an username without Admin privs.
- Make sure navidrome uses the (ND_DEVAUTOLOGINUSERNAME: "Guest") flag.
- Autologin with Aonsoku into said generated User with privs.
- Create an Playlist on an Admin Priv. User. (most likely created on another client eg. Feishin)
- try to delete the generated playlist which was made by said admin user.

Hope this step by step make it easy to replicate.

PS: Ive seen that this behavior is not the case if people try to delete or add radios. i hope you can fix that on playlist as well.

**Comment by victoralvesf** [comment]
Sorry to inform you this, but the app itself doesn't have anything related to permissions, all of this stuff is on the server, in your case Navidrome. The flag `ND_DEVAUTOLOGINUSERNAME` is for Navidrome UI only, the app is only using the regular credentials to login automatically.

Just for you to know, I tried to replicate your scenario in a server without this auto login feature from navidrome, and the server is correctly blocking the playlist exclusion. (Even though the app toast says that was deleted, just a visual bug)

![image](https://github.com/user-attachments/assets/87ac409a-616a-4e72-b93f-875d0ea12b03)

So I have to say that this is a bug from Navidrome, maybe it's related to this auto login hidden feature.

Can you try this scenario with other Subsonic clients? Just to be sure I'm not leaving anything behind.

**Comment by kobayashi90** [comment]
On my end it shows this as output if i am deleting an single song in that playlist made by an Admin User.
![](https://i.imgur.com/rjxUhCN.png)

**Comment by victoralvesf** [comment]
> On my end it shows this as output if i am deleting an single song in that playlist made by an Admin User. ![](https://camo.githubusercontent.com/503b4001a8a71146e4c206afb21d1e8c74adf66033bcd84d8bb9ce0767a89bb5/68747470733a2f2f692e696d6775722e636f6d2f726a785568434e2e706e67)

The request you pointed (`getPlaylist`) is the side effect of removing a song from the playlist, which is the request used to get the playlist with updated data. When removing a song from playlists it uses the `updatePlaylist` request.

**Comment by kobayashi90** [comment]
Even if i am showing you "updatePlaylist" is says nothing about denying the request.
![firefox_pffNhKo4mi](https://github.com/user-attachments/assets/bda51dbb-bb58-48c8-9b56-5440825cdefb)

**Comment by kobayashi90** [comment]
Edit 2: This is what is on my end via Firefox if i am deleting an playlist.
![WDADesktopService_1gKR7XZPmO](https://github.com/user-attachments/assets/0180c68a-25ad-46ca-ac42-4d62f12c5c0c)

**Comment by kobayashi90** [comment]
> So I have to say that this is a bug from Navidrome, maybe it's related to this auto login hidden feature.

Should i try to remove that flag on navidrome? did you had that flag enabled while getting that playlist error?

**Comment by victoralvesf** [comment]
I suggest you to disable this feature Auto Login feature from Navidrome, just to test. If you already uses the App (Aonsoku) Auto Login feature, it won't make any difference.

Let me know what you find. I'm also updating this test server for Navidrome 0.53 just to confirm.

**Comment by victoralvesf** [comment]
Updated to 0.53.3 and server still blocking the exclusion.

![image](https://github.com/user-attachments/assets/91320154-5ecb-4c80-9d8d-a60d9d2657a3)

**Comment by victoralvesf** [comment]
In my case, even activating the flag `ND_DEVAUTOLOGINUSERNAME` for this test, the server blocked the exclusion. Maybe is another config that is allowing the exclusion. This test server config is really simple.

![bug_config](https://github.com/user-attachments/assets/c24e6ba7-6aa4-4cee-a3cd-3ef97c5f8135)

**Comment by kobayashi90** [comment]
Ok so there must be an bug in feishin then, this time ive created the playlist by not selecting make it public first, which fixed the issue. example below.
![Feishin_pXOnVOdU9J](https://github.com/user-attachments/assets/8ad4704c-40d2-43ae-973c-2cafa12706d6)

**Comment by victoralvesf** [comment]
Used your entire config, including my `ND_BASEURL` and `ND_DEVAUTOLOGINUSERNAME` set to my user 'demo', but the server keeps blocking the exclusion.  

I have no clue whatsoever what could be. 😄

**Comment by victoralvesf** [comment]
Closing the issue then.

And the visual bug will be fixed, I'm adding to the backlog.

If the request receives the permission denied error from server, the app will show correctly.

**Comment by kobayashi90** [comment]
> I have no clue whatsoever what could be. 😄

Yeah, ok so since this is practically resolved i am closing this shortly but if you ever try to make this an Windows App via some kind of wrapper (hopefully not electron) make sure this doesnt happen on your app just like feishin does.

**Comment by kobayashi90** [comment]
@victoralvesf please test the following, non admin users can change playlist names which shouldnt be allowed.

**Comment by victoralvesf** [comment]
> @victoralvesf please test the following, non admin users can change playlist names which shouldnt be allowed.

I'm currently taking a break from the project to enjoy the holiday season, but next month I'll look into this scenario. Thanks!

**Comment by victoralvesf** [comment]
> please test the following, non admin users can change playlist names which shouldnt be allowed.

Yeah, this is happening. Navidrome is not taking account user roles in this case. What I can do from Aonsoku side, is create an env variable to control this rule, something like `ALLOW_NON_ADMIN_EDIT_PLAYLISTS`. But if someone knows how the Subsonic API works, will easily be able to edit anyways. I'll include this feature in next improvements.
