### ISSUE TITLE
Making the Search a bit moderate for Bigger Navidrome Servers

### ISSUE THREAD

**Issue by kobayashi90** [victoralvesf/aonsoku#55]
The Problem is that if you access the Songlist Section on Aonsoku is that this request takes forever to resolve.
Screenshot below:
![Screenshot](https://i.imgur.com/R0PxXF0.png)

Search Query:
https://www.squidify.org/rest/search3?u=Guest&t=3a98bc55391946445f6f838063cae8c6&s=40n50kuPl4y3r&v=1.16.0&c=Aonsoku&f=json&query=&artistCount=0&artistOffset=0&albumCount=0&albumOffset=0&songCount=999999999&songOffset=0

**Comment by victoralvesf** [comment]
Hello, thanks for reaching out.

Yes, this is a bit problematic. When I was coding this part of the application, I couldn’t find a better solution at the time. I’ll definitely take a closer look at it in future versions to improve the page. Thanks for bringing this up!
