### ISSUE TITLE
Desktop app availability

### ISSUE THREAD

**Issue by th0th** [victoralvesf/aonsoku#57]
Thank you for building Aonsoku – its UI is one of the best I’ve seen among Navidrome clients! 🎉

I was wondering if you have any estimated timeline for releasing a downloadable desktop app? I’d be happy to lend a hand if there’s any way I can assist with it. 💐

Also, I have a small suggestion: it might be more intuitive to move the language dropdown into the user menu. Switching languages isn’t something most users do frequently, so it might fit better there.

Thanks again for your great work!

**Comment by victoralvesf** [comment]
Thank you so much for the kind words, I’m thrilled to hear that you enjoyed the UI!

Regarding your first question, I haven’t released desktop versions of the app yet, mainly to avoid exceeding the GitHub Actions free tier. However, I’m considering making these available in future releases, so stay tuned!

As for your suggestion about moving the language dropdown to the user menu, that’s a great idea, and I’ll be implementing it in upcoming versions. I'm thinking about moving the theme switch too.

Thanks again for reaching out!
