### ISSUE TITLE
[Chromium engine only] Support seek to any position in the song

### ISSUE THREAD

**Issue by xiaogaozi** [victoralvesf/aonsoku#61]
This seems to be a bug, when I click anywhere in the progress bar of a song the player doesn't jump to that position.

I use Google Chrome 130.0.6723.70.

**Comment by victoralvesf** [comment]
Hi @xiaogaozi, thanks for reaching out.

I just tested the app on this version of Chrome, and the progress slider is working properly. Do you use any kind of transcoding for the app? By default, it relies on the server-provided settings for transcoding.

Could you provide more details so we can work on this? Specifically, it would help to know:

1. If the issue happens only on Chrome.
2. If the issue happens consistently or only under certain conditions.
3. Any particular server configurations or transcoding settings that might be relevant to the app's performance.

This info will allow us to troubleshoot more effectively!

**Comment by xiaogaozi** [comment]
> If the issue happens only on Chrome.

Yes, I tried Firefox 131.0.3, the progress slider works.

> If the issue happens consistently or only under certain conditions.

For Chrome, it happens consistently. I also tried incognito mode, have the same issue.

> Any particular server configurations or transcoding settings that might be relevant to the app's performance.

![CleanShot 2024-10-29 at 15 35 35@2x](https://github.com/user-attachments/assets/f58d5d8c-9442-4fc4-943b-e5cb1eef6ae6)

I didn't turn on the transcoding settings for Aonsoku (as shown in the screenshot above).

By the way, the song format is OGG (Vorbis codec).

**Comment by xiaogaozi** [comment]
I also tried Edge, have the same issue.

**Comment by victoralvesf** [comment]
Thanks for bringing more info. By now I'm suspecting that the issue is caused by the media format, I'm going to do some tests.

**Comment by victoralvesf** [comment]
@xiaogaozi I ran some tests with OGG (Vorbis) media and didn’t encounter any issue, everything worked smoothly on both Chrome and Arc.

Could you check in DevTools to see if the server is correctly sending the estimated content length? This might help to identify any inconsistencies.

<details><summary>Example:</summary>

![image](https://github.com/user-attachments/assets/7829c044-f9a2-4d00-a433-2f5deb3f99f3)

</details> 

Other than that, does this issue occur with all types of media formats?

<details><summary>Test info:</summary>

> macOS Ventura 13.6.4 (22G513)
> Chrome 130.0.6723.70
> Arc 1.66.0 (55166) | Chromium Engine Version 130.0.6723.70

</details>

**Comment by xiaogaozi** [comment]
I have tried song in MP3 format, but the progress slider still doesn't work properly. ☹️

Then I tested it again in Navidrome, and I found that whether the song is in OGG or MP3 format, the progress slider can be used normally.

**Comment by victoralvesf** [comment]
> I have tried song in MP3 format, but the progress slider still doesn't work properly. ☹️
> 
> Then I tested it again in Navidrome, and I found that whether the song is in OGG or MP3 format, the progress slider can be used normally.

Thank you for all the detailed information, it’s very helpful!

Since you confirmed the issue doesn’t occur in Navidrome, and it’s happening consistently across Chromium-based browsers, this suggests it might be related to specific interactions in our app’s environment.

Sorry to keep asking for more info, but I really don’t know how to proceed because I haven’t encountered any issues like this, and I’ve tested it on major browsers and different OSes. Here are some additional steps that could help narrow down the root cause:

1. **Check for Network or CORS Issues:** In Chrome DevTools, go to the Network tab and observe if there are any irregularities in some requests.

2. **Inspect JavaScript Console for Warnings/Errors:** Look in the Console tab in DevTools to see if any errors or warnings appear when adjusting the slider.

3. **Browser Extension Conflict:** If not tested already, double-check for any browser extensions that might interfere, even in incognito mode.

Feel free to let me know what you find from these steps or if there’s any other behavior you notice. I’ll be here to further assist based on the results. Thanks for your continued patience!

**Comment by xiaogaozi** [comment]
I tried to debug the `handleSeeking()` and `handleSeeded()` functions of the [`PlayerProgress`](https://github.com/victoralvesf/aonsoku/blob/main/src/app/components/player/progress.tsx) component, and then I found that when I clicked the slider, the first breakpoint will correctly interrupt the code execution, while the second breakpoint will never be interrupted (see the screenshot below). This means that the `handleSeeked()` function will never be called.

<details>
<summary>Debug screenshot</summary>

![CleanShot 2024-10-31 at 12 26 05@2x](https://github.com/user-attachments/assets/e7076426-c88c-43b2-9ce3-c16242b29838)

</details>

Then I found a possible [related issue](https://github.com/radix-ui/primitives/issues/1760) in the Radix Primitives project. In that issue, someone suggested a [workaround](https://github.com/radix-ui/primitives/issues/1760#issuecomment-2133137759) that might solve this problem.

**Comment by victoralvesf** [comment]
> Then I found a possible related issue in the Radix Primitives project. In that issue, someone suggested a workaround that might solve this problem.

Thanks for debugging the app, now this seams to be the real issue. For what I read in this issue you shared, apparently the problem only occurs when using trackpads. I'll give it a try using the mentioned workaround so you can test.

**Comment by xiaogaozi** [comment]
Thanks. By the way, I'm using the Magic Trackpad.

**Comment by victoralvesf** [comment]
@xiaogaozi could you please check if the issue still occurs in this [preview build](https://aonsoku-git-fix-update-sl-32cc93-victor-alves-projects-ccaa8240.vercel.app?_vercel_share=QKrHukzE9NwXmkwtyYGDOyJZzwaLVJgV)?

**Comment by victoralvesf** [comment]
@xiaogaozi updated, can you check it again?

**Comment by xiaogaozi** [comment]
@victoralvesf I found that this feature does not work in full screen mode. Similarly, this issue only occurs in browsers with the Chromium engine, and it is normal in Safari.
