### ISSUE TITLE
Support for certain Enviorments where you dont need an Login Prompt. (LAN Support)

### ISSUE THREAD

**Issue by kobayashi90** [victoralvesf/aonsoku#83]
I would like to point out that in certain LAN Enviorments its easier to have the option to automaticly login with an set user which doesnt have Admin privileges (similar to what Navidrome does with the **ND_DEVAUTOLOGINUSERNAME: "Guest"** variable.

Would be awesome if that gets supported in the future.
Just hoping for it.

**Comment by kobayashi90** [comment]
@victoralvesf will it be possible to set an fixed design for the webui? (via docker compose i mean)

**Comment by victoralvesf** [comment]
> @victoralvesf will it be possible to set an fixed design for the webui? (via docker compose i mean)

Could you explain? I don't understand what you mean by fixed design.

**Comment by kobayashi90** [comment]
> Could you explain? I don't understand what you mean by fixed design.

As in if i am be able to set an Design in the Docker vars like navidrome does?

**Comment by victoralvesf** [comment]
Are you talking about `ND_DEFAULTTHEME` setting? If so, after the in app settings page is released, I can think clearly what options can be included in docker env vars.

**Comment by victoralvesf** [comment]
Hi @kobayashi90, check it out the README evironment variables section to see how automatic login will work.

**Comment by kobayashi90** [comment]
> Hi @kobayashi90, check it out the README evironment variables section to see how automatic login will work.

Yeah ive tested it, yet ive found the problem ive described before where now the default design is the white theme.
How do i set this to something else permanently or set it as default?
