### ISSUE TITLE
Support Navidrome's Sharing Feature

### ISSUE THREAD

**Issue by kobayashi90** [victoralvesf/aonsoku#89]
Ive noticed that aonsoku pretty much has all major features from navidrome.. except for the sharing feature..
it would be cool if you could add an sharing tab just like on navidrome.
 i know that would add a lot of changes to already existing pages but i think this is mandatory.

**Comment by victoralvesf** [comment]
Unfortunately, this is not a planned feature, as the generated link will open in the origin server (in your case, Navidrome), which is not related to the app itself. Additionally, other Subsonic servers do not have this feature implemented, nor do they have a web interface.
